/** Dream Layer item constants (server-side mirror of src/utils/dreamLayerItems.ts). */

const EXODIA_ARMOR_TYPES = Object.freeze([
  'EXODIA_HELM',
  'EXODIA_PAULDRONS',
  'EXODIA_PLATE',
  'EXODIA_GREAVES',
  'EXODIA_GAUNTLETS',
]);

const HEXMETAL_SET_TYPES = Object.freeze([
  'HEXMETAL_CLOAK',
  'HEXMETAL_LEGGINGS',
  'HEXMETAL_VAMBRACES',
]);

const ARCHMAGE_SET_TYPES = Object.freeze([
  'ARCHMAGE_COIL',
  'ARCHMAGE_BELT',
]);

const DREAM_LAYER_UNIQUE_TYPES = Object.freeze([
  ...EXODIA_ARMOR_TYPES,
  ...HEXMETAL_SET_TYPES,
  'ARCHMAGE_COIL',
  'ARCHMAGE_BELT',
  'PERSEPHONE',
  'WYVERN_AMETHYST',
  'INFINITE_AMBER',
  'LIQUID_SAPPHIRE',
  'JAGUAR_EMERALD',
  'RAZED_DIAMOND',
]);

/** Effect pendants from the warding-pendant slot (not boss/enemy ground drops). */
const EFFECT_PENDANT_TYPES = Object.freeze([
  'HUNTERS_MARK',
  'SOUL_WARD',
]);

const MERCHANT_EXODIA_POOL = Object.freeze([
  ...EXODIA_ARMOR_TYPES,
  ...HEXMETAL_SET_TYPES,
  'ARCHMAGE_COIL',
  'ARCHMAGE_BELT',
]);

/** Pool for boss/enemy ground drops (all unique Dream Layer relics). */
const DREAM_LAYER_LOOT_POOL = DREAM_LAYER_UNIQUE_TYPES;

/** Chance for a Dream Layer relic to drop alongside the normal boss reward. */
const DREAM_LAYER_BOSS_DROP_CHANCE = Object.freeze({
  boss: 0.10,
  boss2: 0.22,
  boss3: 0.40,
  destiny: 0.45,
});

/** Very small chance on non-ghoul enemy deaths. */
const DREAM_LAYER_ENEMY_DROP_CHANCE = 0.005;

/** Elevated chance for Nemesis, Valkyrie, Titan, and Boss1 elite knights. */
const DREAM_LAYER_ELITE_DROP_CHANCE = 0.04;

const DREAM_LAYER_ITEM_DESCRIPTIONS = Object.freeze({
  EXODIA_HELM: 'Kaiser: Critical hits spawn a pillar of fire (195 dmg + Ignite). 2.5s ICD.',
  EXODIA_PAULDRONS: 'Scorpion Lance: After dash charge spent, next primary within 2s fires piercing shard (40+4×AGI). 1.5s ICD.',
  EXODIA_PLATE: 'Hatemail Vest: Taking damage returns 300% of the damage back to the attacker.',
  EXODIA_GREAVES: 'Sleepwalker: Enemies drop double FLOW (2/6/15 shards).',
  EXODIA_GAUNTLETS: 'Vicegrip: Sabres left/right +20 dmg; Runeblade combo +50 dmg. No effect on Scythe/Bow.',
  ARCHMAGE_COIL: 'Arcane Reservoir: Dash charge spent restores 20 Energy. Cannot stack with Exodia Helm. 2pc (with Belt): +15 Intellect.',
  ARCHMAGE_BELT: 'Quickened Mind: Reduces Q ability cooldowns (Frostbite 6s, Wraith Strike 3.75s, Mantra 6s, Backstab 2.75s). 2pc (with Coil): +15 Intellect.',
  HEXMETAL_CLOAK: 'Damage Ward: No single source of damage can exceed 50. 2pc: walk speed 4.125 (no sprint stack). 3pc: +1 dash charge.',
  HEXMETAL_LEGGINGS: 'Momentum Weave: Halves movement speed reduction while attacking. 2pc: walk 4.125. 3pc: +1 dash charge.',
  HEXMETAL_VAMBRACES: 'Swift Arms: Reduces E ability cooldowns (Reaping Talons 5s, Colossus 6s/4.5s Legionnaire, Crossentropy 6s, Flourish 0.75s). 2pc: walk 4.125. 3pc: +1 dash charge.',
  PERSEPHONE: 'Death Goddess: Next fatal blow sets you to 90% HP and consumes the ring. Regenerated by Immortal Union (4pc Exodia).',
  WYVERN_AMETHYST: 'Leviathan Scales: Venom applies Needler stacks; at 4 stacks burst 70+4×INT.',
  INFINITE_AMBER: "Enchanter's Gift: +40% Energy recovery rate.",
  LIQUID_SAPPHIRE: 'Cold Grace: Primary on frozen enemy shatters for +350 damage.',
  JAGUAR_EMERALD: 'Trial by Fire: Red venom theme; +30% crit vs venomed on primary attacks.',
  RAZED_DIAMOND: 'Bloodrose Ember: Q abilities deal up to +250% damage based on missing HP.',
  HUNTERS_MARK: "Hunter's Mark: Your beast companions deal +30 melee damage.",
  SOUL_WARD: 'Soul Bond: Negate a hit and deal double the damage to your ally instead. 6s cooldown.',
});

const DREAM_LAYER_ITEM_LABELS = Object.freeze({
  EXODIA_HELM: 'Exodia Helm',
  EXODIA_PAULDRONS: 'Exodia Pauldrons',
  EXODIA_PLATE: 'Exodia Plate',
  EXODIA_GREAVES: 'Exodia Greaves',
  EXODIA_GAUNTLETS: 'Exodia Gauntlets',
  ARCHMAGE_COIL: 'Archmage Coil',
  ARCHMAGE_BELT: 'Archmage Belt',
  HEXMETAL_CLOAK: 'Hexmetal Cloak',
  HEXMETAL_LEGGINGS: 'Hexmetal Leggings',
  HEXMETAL_VAMBRACES: 'Hexmetal Vambraces',
  PERSEPHONE: 'Persephone',
  WYVERN_AMETHYST: 'Wyvern Amethyst',
  INFINITE_AMBER: 'Infinite Amber',
  LIQUID_SAPPHIRE: 'Liquid Sapphire',
  JAGUAR_EMERALD: 'Jaguar Emerald',
  RAZED_DIAMOND: 'Razed Diamond',
  HUNTERS_MARK: "Hunter's Mark",
  SOUL_WARD: 'Soul Ward',
});

const PERSEPHONE_SAVE_HP_FRACTION = 0.9;

/** Immortal Union (Exodia set) — auto-grant / regenerate Persephone. Requires 4 pieces. */
function hasImmortalUnion(exodiaCount) {
  return (exodiaCount || 0) >= 4;
}

function isUniqueDreamLayerItem(type) {
  return DREAM_LAYER_UNIQUE_TYPES.includes(type);
}

function isEffectPendant(type) {
  return EFFECT_PENDANT_TYPES.includes(type);
}

/** Unique ownership (shop/loot duplicate guards) — includes effect pendants. */
function isUniqueOwnedItem(type) {
  return isUniqueDreamLayerItem(type) || isEffectPendant(type);
}

function getDreamLayerItemDescription(type) {
  return DREAM_LAYER_ITEM_DESCRIPTIONS[type] || 'A legendary relic from the Dream Layer.';
}

function getDreamLayerItemLabel(type) {
  return DREAM_LAYER_ITEM_LABELS[type] || type;
}

function countExodiaPieces(ownedSet) {
  if (!ownedSet || typeof ownedSet.has !== 'function') return 0;
  let n = 0;
  for (const t of EXODIA_ARMOR_TYPES) {
    if (ownedSet.has(t)) n++;
  }
  return n;
}

function ensurePlayerOwnedItems(player) {
  if (!player) return;
  if (!player.ownedUniqueItemTypes) {
    player.ownedUniqueItemTypes = new Set();
  }
}

function playerOwnsItem(player, type) {
  ensurePlayerOwnedItems(player);
  return player.ownedUniqueItemTypes.has(type);
}

function registerPlayerOwnedItem(player, type) {
  ensurePlayerOwnedItems(player);
  if (isUniqueDreamLayerItem(type) || isEffectPendant(type)) {
    player.ownedUniqueItemTypes.add(type);
  }
  if (type === 'PERSEPHONE') {
    player.hasPersephone = true;
    player.persephoneConsumed = false;
  }
  player.exodiaSetCount = countExodiaPieces(player.ownedUniqueItemTypes);
}

function getMerchantExodiaOfferChance(bossesDefeated, segmentRoomsCleared) {
  const depth = (bossesDefeated || 0) + Math.floor((segmentRoomsCleared || 0) / 3);
  const base = 0.08;
  const scaled = Math.min(0.45, base + depth * 0.04);
  return scaled;
}

function rollMerchantExodiaCost() {
  return 800 + Math.floor(Math.random() * 401);
}

module.exports = {
  EXODIA_ARMOR_TYPES,
  HEXMETAL_SET_TYPES,
  ARCHMAGE_SET_TYPES,
  DREAM_LAYER_UNIQUE_TYPES,
  EFFECT_PENDANT_TYPES,
  MERCHANT_EXODIA_POOL,
  DREAM_LAYER_LOOT_POOL,
  DREAM_LAYER_BOSS_DROP_CHANCE,
  DREAM_LAYER_ENEMY_DROP_CHANCE,
  DREAM_LAYER_ELITE_DROP_CHANCE,
  DREAM_LAYER_ITEM_DESCRIPTIONS,
  DREAM_LAYER_ITEM_LABELS,
  PERSEPHONE_SAVE_HP_FRACTION,
  hasImmortalUnion,
  isUniqueDreamLayerItem,
  isEffectPendant,
  isUniqueOwnedItem,
  getDreamLayerItemDescription,
  getDreamLayerItemLabel,
  countExodiaPieces,
  ensurePlayerOwnedItems,
  playerOwnsItem,
  registerPlayerOwnedItem,
  getMerchantExodiaOfferChance,
  rollMerchantExodiaCost,
};
