/** Must match `src/utils/mushroomConstants.ts` gameplay numbers. */
module.exports = {
  MUSHROOM_MAX_HP: 30,
  MUSHROOM_ERUPTION_PLAYER_DMG: 5,
  MUSHROOM_ERUPTION_ENEMY_DMG: 250,
  MUSHROOM_ERUPTION_ALLY_DMG: 25,
  MUSHROOM_ERUPTION_RADIUS: 3.5,
  MUSHROOM_MAX_DAMAGE_PER_HIT: 1500,
};
